In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
data = pd.read_csv('kaggle/input/digit-recognizer/train.csv')

In [ ]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [ ]:
X_train[:, 0].shape

(784,)

In [ ]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [ ]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size * 100

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 2 == 0:
            print("Iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [ ]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 100, 0.01)

<ipython-input-6-9f0ad550be7a>:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-6-9f0ad550be7a>:12: RuntimeWarning: invalid value encountered in true_divide
  A = np.exp(Z) / sum(np.exp(Z))


Iteration:  0
[6 1 1 ... 2 1 5] [3 8 3 ... 8 2 0]
Accuracy:  6.775609756097562
Iteration:  2
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  4
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  6
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  8
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  10
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  12
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  14
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  16
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  18
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  20
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  22
[0 0 0 ... 0 0 0] [3 8 3 ... 8 2 0]
Accuracy:  9.834146341463414
Iteration:  24
[0 0 0 ... 0 0 0] [3 8 3 ... 8